//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_Cobrar
    {
        public int noFactura { get; set; }
        public Nullable<decimal> montoDeuda { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public Nullable<System.DateTime> fechaLimitePago { get; set; }
        public bool estadoPago { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
