//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Cotizacion_Producto = new List<Cotizacion_Producto>();
            this.Cotizacion_Servicio = new List<Cotizacion_Servicio>();
            this.Facturas = new List<Factura>();
        }
    
        public int noCotizacion { get; set; }
        public int cliente { get; set; }
        public decimal subTotal { get; set; }
        public Nullable<decimal> tax { get; set; }
        public decimal total { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public bool state { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Cotizacion_Producto> Cotizacion_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Cotizacion_Servicio> Cotizacion_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Factura> Facturas { get; set; }
    }
}
