//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Cuentas_Cobrar = new List<Cuentas_Cobrar>();
        }
    
        public int noFactura { get; set; }
        public Nullable<int> noCotizacion { get; set; }
        public int cliente { get; set; }
        public string tipoComprobante { get; set; }
        public string comprobanteFiscal { get; set; }
        public string metodoPago { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public bool state { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Cotizacion Cotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Cuentas_Cobrar> Cuentas_Cobrar { get; set; }
    }
}
